// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: pwm

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
    lv_obj_set_style_bg_img_src(ui_Screen1, &ui_img_kkl_240_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_opa(ui_Screen1, 200, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Switch_Mode = lv_switch_create(ui_Screen1);
    lv_obj_set_width(ui_Switch_Mode, 131);
    lv_obj_set_height(ui_Switch_Mode, 18);
    lv_obj_set_x(ui_Switch_Mode, -51);
    lv_obj_set_y(ui_Switch_Mode, -106);
    lv_obj_set_align(ui_Switch_Mode, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_Switch_Mode, LV_STATE_DISABLED);     /// States
    lv_obj_clear_flag(ui_Switch_Mode, LV_OBJ_FLAG_CLICKABLE);    /// Flags
    lv_obj_set_style_bg_color(ui_Switch_Mode, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Switch_Mode, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Switch_Mode, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Switch_Mode, 0, LV_PART_MAIN | LV_STATE_CHECKED);

    lv_obj_set_style_bg_color(ui_Switch_Mode, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Switch_Mode, 0, LV_PART_INDICATOR | LV_STATE_CHECKED);

    lv_obj_set_style_bg_color(ui_Switch_Mode, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Switch_Mode, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Switch_Mode, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Switch_Mode, 200, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Switch_Mode, 2, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Switch_Mode, 2, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Switch_Mode, lv_color_hex(0xFF0000), LV_PART_KNOB | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_Switch_Mode, 200, LV_PART_KNOB | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_color(ui_Switch_Mode, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_opa(ui_Switch_Mode, 200, LV_PART_KNOB | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_width(ui_Switch_Mode, 2, LV_PART_KNOB | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_pad(ui_Switch_Mode, 2, LV_PART_KNOB | LV_STATE_FOCUSED);

    ui_Label_Title = lv_label_create(ui_Switch_Mode);
    lv_obj_set_width(ui_Label_Title, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Label_Title, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_align(ui_Label_Title, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_Title, "PWM Generator");
    lv_obj_set_style_text_decor(ui_Label_Title, LV_TEXT_DECOR_UNDERLINE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Title, &ui_font_SmileySans_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel_Battery = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel_Battery, lv_pct(15));
    lv_obj_set_height(ui_Panel_Battery, lv_pct(7));
    lv_obj_set_x(ui_Panel_Battery, 93);
    lv_obj_set_y(ui_Panel_Battery, -107);
    lv_obj_set_align(ui_Panel_Battery, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel_Battery, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
    lv_obj_set_style_radius(ui_Panel_Battery, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel_Battery, lv_color_hex(0x51FF5D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel_Battery, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Panel_Battery, lv_color_hex(0xFF4F4F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Panel_Battery, 127, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Panel_Battery, 153, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Panel_Battery, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel_Battery, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel_Battery, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel_Battery, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_Battery = lv_label_create(ui_Panel_Battery);
    lv_obj_set_width(ui_Label_Battery, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Label_Battery, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_align(ui_Label_Battery, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_Battery, "60%");
    lv_obj_set_style_text_font(ui_Label_Battery, &ui_font_SmileySans_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button_Switch4 = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_Button_Switch4, lv_pct(17));
    lv_obj_set_height(ui_Button_Switch4, lv_pct(8));
    lv_obj_set_x(ui_Button_Switch4, -90);
    lv_obj_set_y(ui_Button_Switch4, 26);
    lv_obj_set_align(ui_Button_Switch4, LV_ALIGN_TOP_MID);
    lv_obj_add_state(ui_Button_Switch4, LV_STATE_DISABLED);     /// States
    lv_obj_add_flag(ui_Button_Switch4, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);   /// Flags
    lv_obj_clear_flag(ui_Button_Switch4, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
    lv_obj_set_style_radius(ui_Button_Switch4, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button_Switch4, lv_color_hex(0xFECCCC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button_Switch4, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button_Switch4, lv_color_hex(0x987A7A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Button_Switch4, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Button_Switch4, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Button_Switch4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_Button_Switch4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_Button_Switch4, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Button_Switch4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Button_Switch4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Button_Switch4, &ui_font_SmileySans_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button_Switch4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DISABLED);
    lv_obj_set_style_bg_opa(ui_Button_Switch4, 200, LV_PART_MAIN | LV_STATE_DISABLED);

    ui_Label_CH4 = lv_label_create(ui_Button_Switch4);
    lv_obj_set_width(ui_Label_CH4, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Label_CH4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_align(ui_Label_CH4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_CH4, "CH4");

    ui_Button_Switch3 = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_Button_Switch3, lv_pct(17));
    lv_obj_set_height(ui_Button_Switch3, lv_pct(8));
    lv_obj_set_x(ui_Button_Switch3, -45);
    lv_obj_set_y(ui_Button_Switch3, 26);
    lv_obj_set_align(ui_Button_Switch3, LV_ALIGN_TOP_MID);
    lv_obj_add_state(ui_Button_Switch3, LV_STATE_DISABLED);     /// States
    lv_obj_add_flag(ui_Button_Switch3, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);   /// Flags
    lv_obj_clear_flag(ui_Button_Switch3, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
    lv_obj_set_style_radius(ui_Button_Switch3, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button_Switch3, lv_color_hex(0xFECCCC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button_Switch3, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button_Switch3, lv_color_hex(0x987A7A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Button_Switch3, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Button_Switch3, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Button_Switch3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_Button_Switch3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_Button_Switch3, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Button_Switch3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Button_Switch3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Button_Switch3, &ui_font_SmileySans_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button_Switch3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DISABLED);
    lv_obj_set_style_bg_opa(ui_Button_Switch3, 200, LV_PART_MAIN | LV_STATE_DISABLED);

    ui_Label_CH3 = lv_label_create(ui_Button_Switch3);
    lv_obj_set_width(ui_Label_CH3, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Label_CH3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_Label_CH3, -1);
    lv_obj_set_y(ui_Label_CH3, 0);
    lv_obj_set_align(ui_Label_CH3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_CH3, "CH3");

    ui_Button_Switch2 = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_Button_Switch2, lv_pct(17));
    lv_obj_set_height(ui_Button_Switch2, lv_pct(8));
    lv_obj_set_x(ui_Button_Switch2, 0);
    lv_obj_set_y(ui_Button_Switch2, 26);
    lv_obj_set_align(ui_Button_Switch2, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_Button_Switch2, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);   /// Flags
    lv_obj_clear_flag(ui_Button_Switch2, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
    lv_obj_set_style_radius(ui_Button_Switch2, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button_Switch2, lv_color_hex(0xFECCCC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button_Switch2, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button_Switch2, lv_color_hex(0x987A7A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Button_Switch2, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Button_Switch2, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Button_Switch2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_Button_Switch2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_Button_Switch2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Button_Switch2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Button_Switch2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button_Switch2, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DISABLED);
    lv_obj_set_style_bg_opa(ui_Button_Switch2, 200, LV_PART_MAIN | LV_STATE_DISABLED);

    ui_Label_CH2 = lv_label_create(ui_Button_Switch2);
    lv_obj_set_width(ui_Label_CH2, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Label_CH2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_Label_CH2, -1);
    lv_obj_set_y(ui_Label_CH2, 0);
    lv_obj_set_align(ui_Label_CH2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_CH2, "CH2");
    lv_obj_set_style_text_font(ui_Label_CH2, &ui_font_SmileySans_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button_Switch1 = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_Button_Switch1, lv_pct(17));
    lv_obj_set_height(ui_Button_Switch1, lv_pct(8));
    lv_obj_set_x(ui_Button_Switch1, 46);
    lv_obj_set_y(ui_Button_Switch1, 26);
    lv_obj_set_align(ui_Button_Switch1, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_Button_Switch1, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);   /// Flags
    lv_obj_clear_flag(ui_Button_Switch1, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
    lv_obj_set_style_radius(ui_Button_Switch1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button_Switch1, lv_color_hex(0xFECCCC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button_Switch1, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button_Switch1, lv_color_hex(0x987A7A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Button_Switch1, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Button_Switch1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Button_Switch1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_Button_Switch1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_Button_Switch1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Button_Switch1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Button_Switch1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Button_Switch1, &ui_font_SmileySans_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button_Switch1, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DISABLED);
    lv_obj_set_style_bg_opa(ui_Button_Switch1, 200, LV_PART_MAIN | LV_STATE_DISABLED);

    ui_Label_CH1 = lv_label_create(ui_Button_Switch1);
    lv_obj_set_width(ui_Label_CH1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Label_CH1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_Label_CH1, -1);
    lv_obj_set_y(ui_Label_CH1, 0);
    lv_obj_set_align(ui_Label_CH1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_CH1, "CH1");

    ui_Button_Switch0 = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_Button_Switch0, lv_pct(17));
    lv_obj_set_height(ui_Button_Switch0, lv_pct(8));
    lv_obj_set_x(ui_Button_Switch0, 92);
    lv_obj_set_y(ui_Button_Switch0, 26);
    lv_obj_set_align(ui_Button_Switch0, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_Button_Switch0, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);   /// Flags
    lv_obj_clear_flag(ui_Button_Switch0, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
    lv_obj_set_style_radius(ui_Button_Switch0, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button_Switch0, lv_color_hex(0xFECCCC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button_Switch0, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button_Switch0, lv_color_hex(0x987A7A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Button_Switch0, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Button_Switch0, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Button_Switch0, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_Button_Switch0, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_Button_Switch0, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Button_Switch0, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Button_Switch0, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Button_Switch0, &ui_font_SmileySans_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button_Switch0, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DISABLED);
    lv_obj_set_style_bg_opa(ui_Button_Switch0, 200, LV_PART_MAIN | LV_STATE_DISABLED);

    ui_Label_CH0 = lv_label_create(ui_Button_Switch0);
    lv_obj_set_width(ui_Label_CH0, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Label_CH0, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_align(ui_Label_CH0, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_CH0, "CH0");

    ui_Panel_Freq = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel_Freq, 224);
    lv_obj_set_height(ui_Panel_Freq, 32);
    lv_obj_set_x(ui_Panel_Freq, 0);
    lv_obj_set_y(ui_Panel_Freq, -54);
    lv_obj_set_align(ui_Panel_Freq, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel_Freq, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
    lv_obj_set_style_radius(ui_Panel_Freq, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel_Freq, lv_color_hex(0xFF3B3B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel_Freq, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Panel_Freq, lv_color_hex(0xFECCCC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Panel_Freq, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Panel_Freq, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Panel_Freq, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel_Freq, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel_Freq, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Panel_Freq, lv_color_hex(0x987A7A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Panel_Freq, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Panel_Freq, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Panel_Freq, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_Panel_Freq, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_Panel_Freq, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_Freq = lv_label_create(ui_Panel_Freq);
    lv_obj_set_width(ui_Label_Freq, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Label_Freq, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_Label_Freq, -55);
    lv_obj_set_y(ui_Label_Freq, 0);
    lv_obj_set_align(ui_Label_Freq, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_Freq, "Frequence:");
    lv_obj_set_style_text_font(ui_Label_Freq, &ui_font_SmileySans_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Spinbox_Freq = lv_spinbox_create(ui_Panel_Freq);
    lv_obj_set_width(ui_Spinbox_Freq, 92);
    lv_obj_set_height(ui_Spinbox_Freq, 69);
    lv_obj_set_x(ui_Spinbox_Freq, 25);
    lv_obj_set_y(ui_Spinbox_Freq, 5);
    lv_obj_set_align(ui_Spinbox_Freq, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_Spinbox_Freq, LV_OBJ_FLAG_SCROLL_ON_FOCUS | LV_OBJ_FLAG_SCROLL_WITH_ARROW);   /// Flags
    lv_spinbox_set_digit_format(ui_Spinbox_Freq, 4, 0);
    lv_spinbox_set_range(ui_Spinbox_Freq, 0, 9999);
    lv_spinbox_set_step(ui_Spinbox_Freq, round(pow(10, 1 - 1)));
    lv_spinbox_set_value(ui_Spinbox_Freq, 100);


    ui_Label_Freq1 = lv_label_create(ui_Panel_Freq);
    lv_obj_set_width(ui_Label_Freq1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Label_Freq1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_Label_Freq1, 12);
    lv_obj_set_y(ui_Label_Freq1, 0);
    lv_obj_set_align(ui_Label_Freq1, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_Label_Freq1, "Hz");
    lv_obj_set_style_text_font(ui_Label_Freq1, &ui_font_SmileySans_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel_Duty = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel_Duty, 224);
    lv_obj_set_height(ui_Panel_Duty, 32);
    lv_obj_set_x(ui_Panel_Duty, 0);
    lv_obj_set_y(ui_Panel_Duty, -16);
    lv_obj_set_align(ui_Panel_Duty, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel_Duty, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
    lv_obj_set_style_radius(ui_Panel_Duty, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel_Duty, lv_color_hex(0xFF3B3B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel_Duty, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Panel_Duty, lv_color_hex(0xFECCCC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Panel_Duty, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Panel_Duty, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Panel_Duty, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel_Duty, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel_Duty, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Panel_Duty, lv_color_hex(0x987A7A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Panel_Duty, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Panel_Duty, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Panel_Duty, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_Panel_Duty, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_Panel_Duty, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_Duty = lv_label_create(ui_Panel_Duty);
    lv_obj_set_width(ui_Label_Duty, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Label_Duty, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_Label_Duty, -78);
    lv_obj_set_y(ui_Label_Duty, 0);
    lv_obj_set_align(ui_Label_Duty, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_Duty, "Duty:");
    lv_obj_set_style_text_color(ui_Label_Duty, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Duty, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Duty, &ui_font_SmileySans_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Spinbox_Duty = lv_spinbox_create(ui_Panel_Duty);
    lv_obj_set_width(ui_Spinbox_Duty, 92);
    lv_obj_set_height(ui_Spinbox_Duty, 69);
    lv_obj_set_x(ui_Spinbox_Duty, 33);
    lv_obj_set_y(ui_Spinbox_Duty, 5);
    lv_obj_set_align(ui_Spinbox_Duty, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_Spinbox_Duty, LV_OBJ_FLAG_SCROLL_ON_FOCUS | LV_OBJ_FLAG_SCROLL_WITH_ARROW);   /// Flags
    lv_spinbox_set_digit_format(ui_Spinbox_Duty, 3, 0);
    lv_spinbox_set_range(ui_Spinbox_Duty, 0, 100);
    lv_spinbox_set_step(ui_Spinbox_Duty, round(pow(10, 1 - 1)));
    lv_spinbox_set_value(ui_Spinbox_Duty, 50);


    ui_Label_Duty1 = lv_label_create(ui_Panel_Duty);
    lv_obj_set_width(ui_Label_Duty1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Label_Duty1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_Label_Duty1, 8);
    lv_obj_set_y(ui_Label_Duty1, 0);
    lv_obj_set_align(ui_Label_Duty1, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_Label_Duty1, "%");
    lv_obj_set_style_text_color(ui_Label_Duty1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Duty1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Duty1, &ui_font_SmileySans_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel_Gener = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel_Gener, 224);
    lv_obj_set_height(ui_Panel_Gener, 32);
    lv_obj_set_x(ui_Panel_Gener, 0);
    lv_obj_set_y(ui_Panel_Gener, 22);
    lv_obj_set_align(ui_Panel_Gener, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel_Gener, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
    lv_obj_set_style_radius(ui_Panel_Gener, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel_Gener, lv_color_hex(0xFF3B3B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel_Gener, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Panel_Gener, lv_color_hex(0xFECCCC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Panel_Gener, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Panel_Gener, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Panel_Gener, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel_Gener, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel_Gener, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Panel_Gener, lv_color_hex(0x987A7A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Panel_Gener, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Panel_Gener, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Panel_Gener, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_Panel_Gener, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_Panel_Gener, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_Gener = lv_label_create(ui_Panel_Gener);
    lv_obj_set_width(ui_Label_Gener, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Label_Gener, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_Label_Gener, -66);
    lv_obj_set_y(ui_Label_Gener, 0);
    lv_obj_set_align(ui_Label_Gener, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_Gener, "Number:");
    lv_obj_set_style_text_font(ui_Label_Gener, &ui_font_SmileySans_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Spinbox_Gener = lv_spinbox_create(ui_Panel_Gener);
    lv_obj_set_width(ui_Spinbox_Gener, 133);
    lv_obj_set_height(ui_Spinbox_Gener, 69);
    lv_obj_set_x(ui_Spinbox_Gener, 7);
    lv_obj_set_y(ui_Spinbox_Gener, 5);
    lv_obj_set_align(ui_Spinbox_Gener, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_Spinbox_Gener, LV_OBJ_FLAG_SCROLL_ON_FOCUS | LV_OBJ_FLAG_SCROLL_WITH_ARROW);   /// Flags
    lv_spinbox_set_digit_format(ui_Spinbox_Gener, 9, 0);
    lv_spinbox_set_range(ui_Spinbox_Gener, 0, 999999999);
    lv_spinbox_set_step(ui_Spinbox_Gener, round(pow(10, 1 - 1)));
    lv_spinbox_set_value(ui_Spinbox_Gener, 5);


    ui_Label_Gener1 = lv_label_create(ui_Panel_Gener);
    lv_obj_set_width(ui_Label_Gener1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Label_Gener1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_Label_Gener1, 3);
    lv_obj_set_y(ui_Label_Gener1, 0);
    lv_obj_set_align(ui_Label_Gener1, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_Label_Gener1, ">");
    lv_obj_set_style_text_font(ui_Label_Gener1, &ui_font_SmileySans_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel_Sent = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel_Sent, 224);
    lv_obj_set_height(ui_Panel_Sent, 32);
    lv_obj_set_x(ui_Panel_Sent, 0);
    lv_obj_set_y(ui_Panel_Sent, 60);
    lv_obj_set_align(ui_Panel_Sent, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel_Sent, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
    lv_obj_set_style_radius(ui_Panel_Sent, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel_Sent, lv_color_hex(0xFF3B3B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel_Sent, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Panel_Sent, lv_color_hex(0xFECCCC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Panel_Sent, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Panel_Sent, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Panel_Sent, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel_Sent, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel_Sent, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Panel_Sent, lv_color_hex(0x987A7A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Panel_Sent, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Panel_Sent, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Panel_Sent, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_Panel_Sent, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_Panel_Sent, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_Sent = lv_label_create(ui_Panel_Sent);
    lv_obj_set_width(ui_Label_Sent, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Label_Sent, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_Label_Sent, -79);
    lv_obj_set_y(ui_Label_Sent, 0);
    lv_obj_set_align(ui_Label_Sent, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_Sent, "Sent:");
    lv_obj_set_style_text_font(ui_Label_Sent, &ui_font_SmileySans_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_Sent_Num = lv_label_create(ui_Panel_Sent);
    lv_obj_set_width(ui_Label_Sent_Num, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Label_Sent_Num, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_Label_Sent_Num, 3);
    lv_obj_set_y(ui_Label_Sent_Num, 0);
    lv_obj_set_align(ui_Label_Sent_Num, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_Label_Sent_Num, "114514 >");
    lv_obj_set_style_text_letter_space(ui_Label_Sent_Num, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_Label_Sent_Num, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Sent_Num, &ui_font_SmileySans_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button_Gener = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_Button_Gener, 55);
    lv_obj_set_height(ui_Button_Gener, 32);
    lv_obj_set_x(ui_Button_Gener, -83);
    lv_obj_set_y(ui_Button_Gener, 98);
    lv_obj_set_align(ui_Button_Gener, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button_Gener, LV_OBJ_FLAG_SCROLL_ON_FOCUS);   /// Flags
    lv_obj_clear_flag(ui_Button_Gener, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
    lv_obj_set_style_radius(ui_Button_Gener, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button_Gener, lv_color_hex(0xFECCCC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button_Gener, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Button_Gener, &ui_img_send_35px_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_opa(ui_Button_Gener, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_Button_Gener, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_Button_Gener, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button_Gener, lv_color_hex(0x987A7A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Button_Gener, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Button_Gener, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Button_Gener, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_Button_Gener, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_Button_Gener, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button_Gener, lv_color_hex(0xFECCCC), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Button_Gener, 200, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_img_recolor(ui_Button_Gener, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_img_recolor_opa(ui_Button_Gener, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_color(ui_Button_Gener, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_opa(ui_Button_Gener, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_blend_mode(ui_Button_Gener, LV_BLEND_MODE_MULTIPLY, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Button_Pause = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_Button_Pause, 55);
    lv_obj_set_height(ui_Button_Pause, 32);
    lv_obj_set_x(ui_Button_Pause, 0);
    lv_obj_set_y(ui_Button_Pause, 98);
    lv_obj_set_align(ui_Button_Pause, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button_Pause, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);   /// Flags
    lv_obj_clear_flag(ui_Button_Pause, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
    lv_obj_set_style_radius(ui_Button_Pause, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button_Pause, lv_color_hex(0xFECCCC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button_Pause, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Button_Pause, &ui_img_begin_35px_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_opa(ui_Button_Pause, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_Button_Pause, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_Button_Pause, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button_Pause, lv_color_hex(0x987A7A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Button_Pause, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Button_Pause, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Button_Pause, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_Button_Pause, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_Button_Pause, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button_Pause, lv_color_hex(0xFECCCC), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Button_Pause, 200, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_img_src(ui_Button_Pause, &ui_img_stop_35px_png, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_img_recolor(ui_Button_Pause, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_img_recolor_opa(ui_Button_Pause, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_color(ui_Button_Pause, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_opa(ui_Button_Pause, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_blend_mode(ui_Button_Pause, LV_BLEND_MODE_MULTIPLY, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Button_Save = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_Button_Save, 55);
    lv_obj_set_height(ui_Button_Save, 32);
    lv_obj_set_x(ui_Button_Save, 83);
    lv_obj_set_y(ui_Button_Save, 98);
    lv_obj_set_align(ui_Button_Save, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button_Save, LV_OBJ_FLAG_SCROLL_ON_FOCUS);   /// Flags
    lv_obj_clear_flag(ui_Button_Save, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
    lv_obj_set_style_radius(ui_Button_Save, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button_Save, lv_color_hex(0xFFCCCC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button_Save, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Button_Save, &ui_img_save_35px_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_opa(ui_Button_Save, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_Button_Save, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_Button_Save, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button_Save, lv_color_hex(0x987A7A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Button_Save, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Button_Save, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Button_Save, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_Button_Save, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_Button_Save, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_Button_Save, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_img_recolor_opa(ui_Button_Save, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Image1 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image1, &ui_img_lighting_20px_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_Image1, 66);
    lv_obj_set_y(ui_Image1, -107);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);   /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
    lv_obj_set_style_img_recolor(ui_Image1, lv_color_hex(0xFFB500), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_Image1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
}
