// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: pwm

#ifndef _LV_CB_H
#define _LV_CB_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"
#include "ui.h"

    typedef enum {
        FUNC_PWM,
        FUNC_DAC
    }Generator_Func_e;

    typedef struct {
        int32_t pwm_freq[3];
        int32_t pwm_duty[3];
        int32_t pwm_num[3];
        int32_t dac_value[3];
        int32_t dac_time[3];
        Generator_Func_e func_mode;//
        uint8_t ch_current;
        uint8_t ch_dac_last;
        uint8_t ch_pwm_last;
        lv_obj_t* ch_switch_obj[5];
    }lv_cb_param_t;

    void ui_cb_init(void);
    void ui_cb_handler(void);

    void ui_switch_disable(Generator_Func_e mode);
    void ui_switch_check(Generator_Func_e mode, uint8_t ch);
    void ui_switch_ch(lv_event_t* e);
    void ui_switch_title(lv_event_t* e);
    void ui_spinbox_set_style(lv_obj_t* pSpinbox);
    void ui_panel_set_schedule(lv_obj_t* pobj, uint64_t value, uint64_t max);
    void spinbox_change_freq(lv_event_t* e);
    void spinbox_change_generate_num(lv_event_t* e);
    void pwm_start_stop(lv_event_t* e);
    void pwm_generate(lv_event_t* e);

    extern lv_group_t* g;
    extern lv_cb_param_t lv_cb_param;
#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
